### ISSUE TITLE
[Feature Requests] Possible room changes

### ISSUE THREAD

**Issue by jtfen86** [blkerby/MapRandomizer#102]
Not sure if anyone else had these ideas so I figured I'd submit a feature request before I forget ->
1. Randomly add/remove water from rooms
2. Horizontal/vertical flipping/mirroring of rooms
3. Reverse gravity or even changing gravity
4. Randomize item location within a room (Like Lioran's route randomizer, more features from that would be dope)

Do any of these have the possibility of working?

**Comment by kjbranch** [comment]
Unfortunately, they are a lot more work than one might expect, because of the complexity of the logic that is required - even simple changes can have massive impacts, which require a very large amount of time and effort to implement.

- We have wanted to randomize heat and water, but it would require a lot more help from others and isn't looking very likely to happen; if it does, it would probably take years of work. See the issue [here](https://github.com/vg-json-data/sm-json-data/issues/1462).
- Flipping rooms horizontally would have much less logic impact and might be feasible - it is something we are considering for the future. 
- Other transformations (vertical flip, rotations, gravity changes) won't be feasible. Moving items in a room could be possible, but hasn't seemed very appealing to us, so it's likely not worth the effort.

**Comment by kjbranch** [comment]
I went ahead and created a new issue for horizontally mirrored rooms on the sm-json-data repo: https://github.com/vg-json-data/sm-json-data/issues/1687
