### ISSUE TITLE
Freezing room transition

### ISSUE THREAD

**Issue by rezydent** [blkerby/MapRandomizer#7]
# Settings
Generated ROM filename (if available):
smmr-v29-115872772-7865696311543382796

# Describe the bug
While going from Big Pink to where would be the hopper e tank (in this case path to get Space Jump) softlocks me during the room transition. As a result it locks you out of Space Jump unless you somehow manage to do one of the clip throughs while doing the loop in reverse, but that's out of the difficulty range.
That might not even be the problem with the randomizer itself but with the quirks of the game, but just giving a heads up.

Amazing randomizer btw. It's way better than door randomizer.

**Comment by blkerby** [comment]
Thanks for reporting this! It turns out it's a problem with entering the Tourian Eye Door room, and it's a major bug affecting every seed. We were applying a couple patches that affect this room, but the order in which they are applied got switched around in today's release (part of the Rust migration) and it resulted in a conflict which broke the room. We'll fix this in v30 which we plan to push out later today.
